### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by tura08** [ar1st0crat/NWaves#1]
How do you feel about putting this on Nuget? Would you be willing to accept a PR that includes:
- Updating the project file format to 2017 style?
- Changing the project target to netstandard2.0?
- Creating an appveyor account for this in order to introduce CI and to build the nuget package?

I'd be happy to contribute to this as I think .NET is in need of a decent signal processing library.

**Comment by ar1st0crat** [comment]
Yes, I've been thinking about Nuget integration from the very day I started working on this lib. Until recently there was no visible interest in this repo by .NET folks, so I was just coding in "relaxed mode". And maybe I'm too perfectionist, but right now I wouldn't want NWaves to be put on Nuget. Although most algorithms are coded properly and give valid results, some parts are not well tested and some interfaces, perhaps, need to be redesigned.

Anyway, thanks for your feedback and your interest. I hope in the nearest future I'll cleanup the code, write some docs and finally create a humble first version of this lib on Nuget. Let's see how it will go. If the developers get eventually interested in this lib, your PR will be of help.

**Comment by tura08** [comment]
Ok, that's completely understandable. Let's see how it evolves, and I'd be happy to contribute in any way I can.

**Comment by Heshyo** [comment]
Please update the readme to add `https://www.nuget.org/packages/NWaves/`.

**Comment by Tesenka** [comment]
Hey I'm trying to open this project in VS2017 and having issues with the XML namespace and MSBuild 2003 etc. Does this have something to do with the project file format 2017 that you mention above?

**Comment by Heshyo** [comment]
@Tesenka Looking at the content of the last NuGet version, I see `.NET Framework 4.7.2`. It seems you're using `v4.6.2`. Either upgrade to 4.7.2, or check an older NuGet version.

**Comment by Tesenka** [comment]
> @Tesenka Looking at the content of the last NuGet version, I see .NET Framework 4.7.2. It seems you're using v4.6.2. Either upgrade to 4.7.2, or check an older NuGet version.

Similarly if I try to install targeting 4.7.2 I get the exact same error, but swap 4.62 for 4.7.2

**Comment by ar1st0crat** [comment]
@Tesenka , have you solved your problem? Every version of .NET Framework starting from 4.6.1 should work OK, since this lib is under .NET Standard 2.0. I created the project referencing ver.4.6.1 in VS2019, and everything worked fine. Sorry, I can't test it right now in VS2017.

**Comment by Tesenka** [comment]
> @Tesenka , have you solved your problem? Every version of .NET Framework starting from 4.6.1 should work OK, since this lib is under .NET Standard 2.0. I created the project referencing ver.4.6.1 in VS2019, and everything worked fine. Sorry, I can't test it right now in VS2017.

I assume the issue is related to using Visual Studio 2015 (which I'm running on this PC)
