### ISSUE TITLE
MFCC returns -Infinity

### ISSUE THREAD

**Issue by stefanpantic** [ar1st0crat/NWaves#10]
Hello, I am getting -Infinity values when I try to run MFCC on my audio file. Any info on where this could occur? All of the values in the input file are normal (i.e. not NaN or Infinity).

**Comment by ar1st0crat** [comment]
Hello! Can you show your code? What parameters are you passing to MFCC constructor? What is the sampling rate of the signal?

**Comment by stefanpantic** [comment]
Here's the ```MfccExtractor``` constructor

```
private static readonly MfccExtractor MfccExtractor = new MfccExtractor(
            16000, 
            13, 
            0.025, 
            0.01, 
            20,
            fftSize:512, 
            preEmphasis:0.97,
            includeEnergy:true,
            dctType:"2",
            nonLinearity:NonLinearityType.LogE);

```

And here's the usage:
```
var stream = new FileStream(file, FileMode.Open);
var waveFile = new WaveFile(stream);
var samples = waveFile[Channels.Left].Samples;
var mfccsamples = MfccExtractor.ParallelComputeFrom(samples);                   
```

**Comment by ar1st0crat** [comment]
OK, actually, it's not a big deal - "-Infinity" energy simply means that the processed block contains only zeros. Currently the code is:

https://github.com/ar1st0crat/NWaves/blob/fb0c1d338c191431fbb2f3763b855ee13005294f/NWaves/FeatureExtractors/MfccExtractor.cs#L312-L314

It needs to be changed (maybe, in next version):

```C#
if (_includeEnergy)
{
    var en = block.Sum(x => x * x);
    mfccs[0] = en > 0 ? (float)(Math.Log(en)) : 0;
}
```

In your resulting vectors you can simply replace this 'infinities' with zeros. The coefficients are fine. Only energy is infinity.

**Comment by ar1st0crat** [comment]
Closin' it, since the reason has been figured out. Personally I'm quite OK with the current behaviour and I would treat ```log-energy = -∞``` as the marker value for discarding vectors computed from zero-frames.
