### ISSUE TITLE
Redesign feature vectors

### ISSUE THREAD

**Issue by ar1st0crat** [ar1st0crat/NWaves#14]
At earlier development stages I focused more on offline processing and I thought ```FeatureVector``` class was good design choice for storing both feature vectors (as ```float[]```) and time positions (as ```double```). But now I think the time position is kind of redundant here. The vector of time positions can easily be computed in a separate method if necessary. Hence, in ver.0.9.3 I'm planning to remove the class ```FeatureVector``` and simply use ```float[]``` arrays for features instead.

If there any ideas or objections you can write them in comments here.

**Comment by ToGoOrNotToGo** [comment]
Is it realy redundant? Otherwise the frame size is needed to calculate the time position from the feature array...

**Comment by ar1st0crat** [comment]
The thing is, each feature extractor object stores the frame size and the hop size for computations anyway. So I think the following design will be fine:

```C#
var extractor = new MfccExtractor(sr, 0.32, 0.1, ...);

List<float[]> mfccs = extractor.ComputeFrom(samples);

// if necessary:
var timeMarkers = extractor.TimeMarkers(samples);
```

Also, user should be able to specify the starting time:

```C#
var timeMarkers = extractor.TimeMarkers(samples, startFrom: 2.64/*sec*/);
```

And maybe this overloaded method will be useful:

```C#
var timeMarkers1 = extractor.TimeMarkers(samples1);
var timeMarkers2 = extractor.TimeMarkers(samples2, continue: true);
```

And, of course, these overloaded methods will remain:

```C#
extractor.ComputeFrom(samples);
extractor.ComputeFrom(samples, startSample: 1000, endSample: 64000);

extractor.TimeMarkers(samples);
extractor.TimeMarkers(samples, startSample: 1000, endSample: 64000);
```

**Comment by ar1st0crat** [comment]
[Done in ver.0.9.3](https://github.com/ar1st0crat/NWaves/wiki/Known-bugs-and-changelog#version-093)
