### ISSUE TITLE
FFT Inverse return not normalized samples

### ISSUE THREAD

**Issue by ToGoOrNotToGo** [ar1st0crat/NWaves#20]
FFT Inverse return not normalized samples. Is there any reason? Other libraries return normalized samples. Why some normalize and some not?
Normalization influence other calculations like cepstrum. The result of an cepstrum is totaly different if the inverse FFT is normalized or not...

**Comment by ar1st0crat** [comment]
Hi @ToGoOrNotToGo !
Your remark is reasonable. There are at least 2 techniques for FFT normalization:
1) FFT: no change; IFFT: divide by N
2) FFT: divide by sqrt(N); IFFT: divide by sqrt(N)

Hence, I decided not to apply any kind of normalization in corresponding methods leaving it to user (yes, it leads to ```IFFT(FFT(X)) != X```). *Normalization can be applied in -Spectrum- methods, though*.
I guess, I won't touch currently existing methods ```Direct``` and ```Inverse``` in ```Fft``` class. But I'll add *"normalized"* methods (just like in ```Dct``` classes) to ```Fft```.

**Comment by ToGoOrNotToGo** [comment]
OK cool. I am waiting for it :-)
I found this:
[](https://dsp.stackexchange.com/questions/11376/why-are-magnitudes-normalised-during-synthesis-idft-not-analysis-dft)

What's your plan with this project? Further developments and/or improvements?

**Comment by ar1st0crat** [comment]
I added simple methods under the common name ```InverseNorm()``` to all Fft classes. These methods return samples normalized by the Fft size.
As for my plans, I'd like to (1) add 3d audio functions, (2) add more feature related to audio synthesis, (3) add "reconstructors" - objects whose purpose is opposite to that of feature extractors, i.e. reconstructing signals from sequences of audio features.
I'm not quite sure that it'll happen soon, though... ))
