### ISSUE TITLE
Nuget installation issues targeting .NetFramework 4.5

### ISSUE THREAD

**Issue by efakhri** [ar1st0crat/NWaves#22]
Hi,
I tried to add NWaves to my project and i get the following error:
"Install-Package : Could not install package 'NWaves 0.9.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that 
framework. For more information, contact the package author."

thank you for your help.

Best Regards,
Fakhri

**Comment by ar1st0crat** [comment]
Hi, @efakhri !
NWaves targets .NET Standard 2.0 [supported only by .NET framework versions starting from 4.6.1](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support).

If you can't switch to 4.6.1 for some reason, you can compile your own NWaves.dll quite easily: 1) clone (or download this repo); 2) create .NET 4.5 class library project; 3) add all downloaded folders with code to project; 4) install ```System.ValueType``` package via NuGet; 5) add reference to ```System.Numerics``` and ```System.Runtime.Serialization``` (they are not included by default); 6) compile!

If you use older Visual Studio, you'll also need to install NuGet package ```Microsoft.Net.Compilers``` for supporting modern C# features.
