### ISSUE TITLE
RealFft Inverse wrong amplitude

### ISSUE THREAD

**Issue by ToGoOrNotToGo** [ar1st0crat/NWaves#23]
Compared to `FFTW.PlanDftComplexToReal1D` the real inverse amplitude from NWaves is factor 2 smaller. So the Unit-Test `TestFft.TestInverseRealFft` should be
`Assert.Multiple(() =>
            {
                Assert.That(output, Is.EqualTo(array.Select(a => a * 8)).Within(1e-5));
                Assert.That(outputNorm, Is.EqualTo(array).Within(1e-5));
            });
`

and the `RealFft.Inverse` methode must be fixed.

Am I wrong?

**Comment by ar1st0crat** [comment]
Yes, you're right!
I should have tested this part more carefully.
I've committed the fix for this issue.
