### ISSUE TITLE
HartleyTransform.Direct has wrong results

### ISSUE THREAD

**Issue by ToGoOrNotToGo** [ar1st0crat/NWaves#24]
The spectrum from HartleyTransform.Direct has wrong results. Results containing not the frequencies from a generated signal (e.g. sine + sine + sine). The result from FHT should be comparable with the FFT result. Right?

**Comment by ar1st0crat** [comment]
I used [very simple formula for computing DHT from FFT](https://en.wikipedia.org/wiki/Hartley_transform):

```dht[i] = real(fft[i]) - imag(fft[i])```

The only problem here is that it's just as fast as FFT, whereas *real* Fast Hartley Transform algorithm is actually slightly faster than FFT.

I tested it against MathNet.Numerics as well. The results are essentially the same:

```C#
using System;
using System.Linq;
using NWaves.Transforms;
using MathNet.Numerics.IntegralTransforms;

//...

// NWaves:
		
var x = new float[] { 1, 5, 2, 8, 5, 23, 8, 1, 9, 9, 2, 12, 31, 0, 8, 17 };
new HartleyTransform(16).Direct(x);

// MathNet.Numerics
		
var d = new double[] { 1, 5, 2, 8, 5, 23, 8, 1, 9, 9, 2, 12, 31, 0, 8, 17 };
var dx = Hartley.NaiveForward(d, HartleyOptions.NoScaling);
		
		
// Result:
		
foreach (var el in x)
    Console.Write(el + " ");
		
// Difference:
		
Console.WriteLine();
for (var i = 0; i < x.Length; i++)
    Console.Write(x[i] - dx[i] + " ");
```
