### ISSUE TITLE
size of istft is not same size of input signal

### ISSUE THREAD

**Issue by hungcuiga1** [ar1st0crat/NWaves#34]
when i get input signal audio,size of signal is:
![image](https://user-images.githubusercontent.com/44896903/95970580-5280d900-0e3a-11eb-8455-d312da18bc16.png)
but i use stft.Inverse size of the result is different input:
![image](https://user-images.githubusercontent.com/44896903/95970785-8d830c80-0e3a-11eb-89f5-593021f63150.png)
how to make it sample. please help me!

**Comment by ar1st0crat** [comment]
Hi,

There are quite a lot nuances related to STFT. Without diving deep into details: the reconstructed signal may have slightly different length. If there's a need, truncate it:

```C#
reconstructed = reconstructed.Take(4608).ToArray();
```

Regards,
Tim
