### ISSUE TITLE
Why are the default lower frequency from FilterBanks.OctaveBands is 62.5?

### ISSUE THREAD

**Issue by ToGoOrNotToGo** [ar1st0crat/NWaves#36]
Why is the default lower frequency of FilterBanks.OctaveBands 62.5? Should it be 11, 22, 44 as specified in ISO 266?
Lower Frequencies: 11, 22, 44, 88, 177, 355, 710, 1420, 2840, 5680, 11360
Middle Frequencies: 16, 31.5, 63, 125, 250, 500, 1000, 2000, 4000, 8000, 16000
Upper Frequencies: 22, 44, 88, 177, 355, 710, 1420, 2840, 5680, 11360, 22720

**Comment by ar1st0crat** [comment]
[In MPEG-7 default lower frequency is 62.5 Hz](https://www.researchgate.net/figure/MPEG-7-NASE-subband-decomposition-with-spectral-resolution-r-12_fig1_224436864)

Anyway, you can set your own lower frequency:

```C#

var octaveBands = Filterbanks.OctaveBands(octaveCount, samplingRate, lowFreq: 22);

```

Everything is customizable here.
You can create your own filterbank, completely from scratch:

```C#

var octaveBands = new [] 
{
    (11,  16,  22),
    (22,  31.5, 44),
    (44, 63, 88),
    //...
    (11360, 16000, 22720)
};

var filterbank = FilterBanks.Rectangular(fftSize, samplingRate, octaveBands);

```
