### ISSUE TITLE
How to use the SOS transfer functions as a filter?

### ISSUE THREAD

**Issue by ToGoOrNotToGo** [ar1st0crat/NWaves#38]
How to use the transfer functions from DesignFilter.TfToSos and apply the filter direct?
Is it possible with NWaves?

**Comment by ar1st0crat** [comment]
You can use ```FilterChain``` class:

```C#

var tf = new TransferFunction(num, den);
var sos = DesignFilter.TfToSos(tf);
var filter = new FilterChain(sos);
var y = filter.ApplyTo(x);

```

[NWaves DSP cheatsheet](https://github.com/ar1st0crat/NWaves/wiki/NWaves-for-MATLAB-and-sciPy-users)

[More about SOS (with C# code in the end)](https://colab.research.google.com/drive/1A_y7sTt3qJoQMyhSv-tOT_pv6-pk4a8d?usp=sharing#scrollTo=qHTN4RYZJTID)

**Comment by ToGoOrNotToGo** [comment]
Oh, sorry, I didn't find this page on your wiki.
Cool stuff! Thanks a lot!
