### ISSUE TITLE
preemphasis filter in LPCExtractor doesn't work

### ISSUE THREAD

**Issue by YaroslavIngvarsson** [ar1st0crat/NWaves#5]
If the preemphasis coefficient is not 0, LPCExtractor returns incorrect results, because the signal is copied to 2 different arrays for autocorrelation function, but preemphasis function is applied to only one array. Same thing with LPCCExtractor.

**Comment by ar1st0crat** [comment]
Indeed! Thanks!
Nuget package will be updated as soon as I'll add couple more things for version 0.9.1.
