### ISSUE TITLE
XML documentation and IntelliSense

### ISSUE THREAD

**Issue by luthfiampas** [ar1st0crat/NWaves#50]
Hi @ar1st0crat 
If we install NWaves from Nuget, XML documentation/comments are not available with IntelliSense. I think adding `<GenerateDocumentationFile>true</GenerateDocumentationFile>` tag in the .csproj file would be really helpful :)

**Comment by ar1st0crat** [comment]
Hi @luthfiampas 
Yes, definitely. I didn't even notice this (I thought this feature was activated by default )))
Thanks for the suggestion
