### ISSUE TITLE
Playing saved audio 

### ISSUE THREAD

**Issue by Amin-Develop** [ar1st0crat/NWaves#57]
Hi, when I save a wave file as the output like this 
`waveFile.SaveTo(stream);`
it will save successfully. 
but it can't Play it with [Media Player](https://developer.android.com/reference/android/media/MediaPlayer) in some devices like Xiaomi devices. but it works on Samsung device 
Can do something to make the output playable on all android devices?

**Comment by ar1st0crat** [comment]
How do you expect me to answer your question without any details? Show your code. Maybe you're passing wrong playback parameters. What do you mean by 'it can't play'? Is it just a silence? Or does your app throw exceptions?

Did you try opening your saved WAV file on PC, in NWaves demo apps (I assume you're saving it like [I suggested here](https://github.com/ar1st0crat/NWaves/issues/56#issuecomment-1013931943))? If it's loaded OK, then everything's fine, and your problems are not related to NWaves library.

**Comment by Amin-Develop** [comment]
I don't think this issue relates to my code because the recorder and saved audio can play on windows and Samsung devices and also on Huawei devices. 
this issue is just with Xiaomi devices which.
my mean of 'it can't play' is just silence and there is no exception.
the code is just the same as my [previous question](https://github.com/ar1st0crat/NWaves/issues/56#issuecomment-1013931943) 
maybe I should ask this question in the Xiaomi community.
