### ISSUE TITLE
Is there method for series filter? or parallel filter?

### ISSUE THREAD

**Issue by pokjnb** [ar1st0crat/NWaves#65]
as the title
I want to parallel connection few butterworthfilters for LR filter,  does it work by using NWaves?
I have checked the notes of Nwaves, but havent seen the similar function, maybe I missed something. Please give some guide, thanks.

**Comment by ar1st0crat** [comment]
Here: [Parallel/Sequential filtering](https://github.com/ar1st0crat/NWaves/wiki/Filters#combining-filters).

Also, there's a class called FilterChain that can be used for online and offline filtering if several filters should be applied one after another (i.e. connected sequentially):

```C#
var chain = new FilterChain(new[] { filter1, filter2 });

//while (new sample is available)
{
    var outputSample = chain.Process(sample);
    // ...
}

// or chunks:
void GotNewChunk(float[] chunk)
{
    chain.Process(chunk, chunk);
}

chain.Reset();
```

At any time new filter can be added to the chain or removed:

```C#
chain.Add(filter3);
chain.RemoveAt(0);
```

**Comment by pokjnb** [comment]
I havent check wiki page, thanks for your guide. You are reaaally efficient, and solve the issue accurately.
I will reopen it if I have using problem. Thnaks again, for your work, this library is good.
