### ISSUE TITLE
LPC exctractor System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by YaroslavIngvarsson** [ar1st0crat/NWaves#7]
Pre-emphasis filter in LPCExtractor prepares initial sample for the next iteration. If it's the last iteration because of the end of the sample, it throws an exception. Same thing with LPCCExtractor.

**Comment by ar1st0crat** [comment]
As far as I understand, it throws exception if hop size is greater than frame size. It's very unusual situation, so I didn't even consider it . But for universality, I guess, this additional check should be there.

**Comment by YaroslavIngvarsson** [comment]
oops, yeah. I messed up and made hop size larger than frame size.
