### ISSUE TITLE
Order of instruction wrong on wiki page

### ISSUE THREAD

**Issue by TrianecT-Wouter** [ar1st0crat/NWaves#84]
on this page:

https://github.com/ar1st0crat/NWaves/wiki/Notes-for-non~experts-in-DSP#how-to-setup-my-filter-and-get-it-working

the example shows:

`var filter = new Butterworth.HighPassFilter(order, f);`

from the code (https://github.com/ar1st0crat/NWaves/blob/master/NWaves/Filters/Butterworth/HighPassFilter.cs#L26) it looks like it should be:

`var filter = new Butterworth.HighPassFilter(f, order);`

**Comment by ar1st0crat** [comment]
Good catch, thanks. Fixed. I didn't even pay attention earlier to the inconsistency between IIR and FIR design method prototypes and the order of parameters (e.g. in `FirWinLp` it's different). Not crucial, I guess, but annoying :(
