### ISSUE TITLE
Butterworth, Chebyshev and Bessel Filter

### ISSUE THREAD

**Issue by ToGoOrNotToGo** [ar1st0crat/NWaves#9]
Hi. I use your Tool to learn some Signal Processing techniques. I like it and the code is very clean. There is already implemented the IIR Butterworth low pass filter. What about all other band forms (high pass, bandpass, stopband/notch)? What about Chebyshev and Bessel filter families? Hop you can implement this filters too!

**Comment by ar1st0crat** [comment]
Hi! Thanks for the kind words. I've never dealt with Chebyshev and Bessel filters, but I'll put them on my list.  When I figure out the math ))) and have some time, I'll add the code and write about it here.

**Comment by ar1st0crat** [comment]
I've added code for Butterworth, Chebyshev-I and II, Bessel and Elliptic filters (LP/HP/BP/BS forms). These changes will go to version 0.9.2 of NuGet package (it's not updated yet, because I'm thinking of including a couple more features to it).
Feel free to reopen this issue if you have any questions or face a problem.

**Comment by ToGoOrNotToGo** [comment]
Wow. Well done! The easiest way for me to learn math is to read code ;-)
More features? Cool! What about FIR-Equiripple?

**Comment by ToGoOrNotToGo** [comment]
Nice, FIR-Equiripple is there! One question. Is it possible to estimate the ripple weight? To simplify the configuration and find the best weight... for linearity...

**Comment by ar1st0crat** [comment]
Hi! Does this [link](https://dsp.stackexchange.com/questions/22017/how-to-manipulate-attenuation-in-parks-mclellan-algorithm) answer your question? In short, the Parks-McClellan algorithm essentially "looks" at the ratio ```delta_passband / delta_attenuate```. Although the weights are set based on particular dB specifications, the algorithm may not converge to that values. We can achieve, say, 40dB attenuation, but perhaps we'll need to tweak the ```delta_passband``` parameter. Is there a way to estimate the best *ratio*? Maybe there are some papers regarding this problem, but I'm not aware of any such work.

PS. I'm also workin' on Jupyter notebook about nuances of implementation of PM algorithm. Soon I'll commit it to repo. Maybe it'll also be helpful. I wish I had such notebook before I spent those hours trying to figure out 'why is it doesn't converge?!!' ))))

**Comment by ToGoOrNotToGo** [comment]
Thanks for answering. At the moment I'm on traveling. So almost no internet. I will look into that ratio estimation if I'm back again.

Is there a Jupyter notebook for C#? Or do you test the algorithm in a different language?

**Comment by ar1st0crat** [comment]
Yes, I often test various algorithms and ideas using Python. I like this language very much ) So I was talking about Jupyter notebook with Python code. In C# world there's also a tool called Xamarin Workbook that resembles Jupyter notebook. It can be used as a simple sandbox or a playground, but it's far less powerful and elaborated for scientific tasks.
